_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
T_max:
    value: 10
decoder_attention_type:
    value: scse
dropout:
    value: 0.2
epochs:
    value: 40
eta_min:
    value: 0.0003
in_channels:
    value: 1
init_lr:
    value: 0.005
weight_decay:
    value: 0.05
